// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: todo/pb/todo-category.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoryTodo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *CategoryTodo) Reset() {
	*x = CategoryTodo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todo_pb_todo_category_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryTodo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryTodo) ProtoMessage() {}

func (x *CategoryTodo) ProtoReflect() protoreflect.Message {
	mi := &file_todo_pb_todo_category_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryTodo.ProtoReflect.Descriptor instead.
func (*CategoryTodo) Descriptor() ([]byte, []int) {
	return file_todo_pb_todo_category_proto_rawDescGZIP(), []int{0}
}

func (x *CategoryTodo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryTodo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryTodo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CategoryTodo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListCategoryTodoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryTodos []*CategoryTodo `protobuf:"bytes,1,rep,name=category_todos,json=categoryTodos,proto3" json:"category_todos,omitempty"`
}

func (x *ListCategoryTodoResponse) Reset() {
	*x = ListCategoryTodoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todo_pb_todo_category_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCategoryTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoryTodoResponse) ProtoMessage() {}

func (x *ListCategoryTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_pb_todo_category_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoryTodoResponse.ProtoReflect.Descriptor instead.
func (*ListCategoryTodoResponse) Descriptor() ([]byte, []int) {
	return file_todo_pb_todo_category_proto_rawDescGZIP(), []int{1}
}

func (x *ListCategoryTodoResponse) GetCategoryTodos() []*CategoryTodo {
	if x != nil {
		return x.CategoryTodos
	}
	return nil
}

type GetCategoryTodoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryTodo *CategoryTodo `protobuf:"bytes,1,opt,name=category_todo,json=categoryTodo,proto3" json:"category_todo,omitempty"`
}

func (x *GetCategoryTodoResponse) Reset() {
	*x = GetCategoryTodoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todo_pb_todo_category_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCategoryTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryTodoResponse) ProtoMessage() {}

func (x *GetCategoryTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_pb_todo_category_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryTodoResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryTodoResponse) Descriptor() ([]byte, []int) {
	return file_todo_pb_todo_category_proto_rawDescGZIP(), []int{2}
}

func (x *GetCategoryTodoResponse) GetCategoryTodo() *CategoryTodo {
	if x != nil {
		return x.CategoryTodo
	}
	return nil
}

type GetCategoryTodoByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCategoryTodoByIDRequest) Reset() {
	*x = GetCategoryTodoByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todo_pb_todo_category_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCategoryTodoByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryTodoByIDRequest) ProtoMessage() {}

func (x *GetCategoryTodoByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_pb_todo_category_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryTodoByIDRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryTodoByIDRequest) Descriptor() ([]byte, []int) {
	return file_todo_pb_todo_category_proto_rawDescGZIP(), []int{3}
}

func (x *GetCategoryTodoByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateCategoryTodoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateCategoryTodoRequest) Reset() {
	*x = CreateCategoryTodoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todo_pb_todo_category_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCategoryTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryTodoRequest) ProtoMessage() {}

func (x *CreateCategoryTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_pb_todo_category_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryTodoRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryTodoRequest) Descriptor() ([]byte, []int) {
	return file_todo_pb_todo_category_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCategoryTodoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_todo_pb_todo_category_proto protoreflect.FileDescriptor

var file_todo_pb_todo_category_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x74, 0x6f, 0x64, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x2d, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xa8, 0x01, 0x0a, 0x0c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x54,
	0x6f, 0x64, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x56, 0x0a,
	0x18, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x54, 0x6f, 0x64,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0e, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x74, 0x6f, 0x64, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x0d, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x54, 0x6f, 0x64, 0x6f, 0x73, 0x22, 0x53, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x38, 0x0a, 0x0d, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x74, 0x6f, 0x64,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x0c, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x22, 0x2c, 0x0a, 0x1a, 0x47, 0x65,
	0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x42, 0x79, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xc1, 0x02, 0x0a, 0x13, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x44, 0x0a, 0x07, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x42,
	0x79, 0x49, 0x44, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x42, 0x79, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_todo_pb_todo_category_proto_rawDescOnce sync.Once
	file_todo_pb_todo_category_proto_rawDescData = file_todo_pb_todo_category_proto_rawDesc
)

func file_todo_pb_todo_category_proto_rawDescGZIP() []byte {
	file_todo_pb_todo_category_proto_rawDescOnce.Do(func() {
		file_todo_pb_todo_category_proto_rawDescData = protoimpl.X.CompressGZIP(file_todo_pb_todo_category_proto_rawDescData)
	})
	return file_todo_pb_todo_category_proto_rawDescData
}

var file_todo_pb_todo_category_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_todo_pb_todo_category_proto_goTypes = []interface{}{
	(*CategoryTodo)(nil),               // 0: proto.CategoryTodo
	(*ListCategoryTodoResponse)(nil),   // 1: proto.ListCategoryTodoResponse
	(*GetCategoryTodoResponse)(nil),    // 2: proto.GetCategoryTodoResponse
	(*GetCategoryTodoByIDRequest)(nil), // 3: proto.GetCategoryTodoByIDRequest
	(*CreateCategoryTodoRequest)(nil),  // 4: proto.CreateCategoryTodoRequest
	(*timestamppb.Timestamp)(nil),      // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 6: google.protobuf.Empty
}
var file_todo_pb_todo_category_proto_depIdxs = []int32{
	5, // 0: proto.CategoryTodo.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: proto.CategoryTodo.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: proto.ListCategoryTodoResponse.category_todos:type_name -> proto.CategoryTodo
	0, // 3: proto.GetCategoryTodoResponse.category_todo:type_name -> proto.CategoryTodo
	6, // 4: proto.CategoryTodoService.FindAll:input_type -> google.protobuf.Empty
	3, // 5: proto.CategoryTodoService.FindByID:input_type -> proto.GetCategoryTodoByIDRequest
	4, // 6: proto.CategoryTodoService.Create:input_type -> proto.CreateCategoryTodoRequest
	3, // 7: proto.CategoryTodoService.Delete:input_type -> proto.GetCategoryTodoByIDRequest
	1, // 8: proto.CategoryTodoService.FindAll:output_type -> proto.ListCategoryTodoResponse
	2, // 9: proto.CategoryTodoService.FindByID:output_type -> proto.GetCategoryTodoResponse
	2, // 10: proto.CategoryTodoService.Create:output_type -> proto.GetCategoryTodoResponse
	6, // 11: proto.CategoryTodoService.Delete:output_type -> google.protobuf.Empty
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_todo_pb_todo_category_proto_init() }
func file_todo_pb_todo_category_proto_init() {
	if File_todo_pb_todo_category_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_todo_pb_todo_category_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryTodo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todo_pb_todo_category_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCategoryTodoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todo_pb_todo_category_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCategoryTodoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todo_pb_todo_category_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCategoryTodoByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todo_pb_todo_category_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCategoryTodoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_todo_pb_todo_category_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todo_pb_todo_category_proto_goTypes,
		DependencyIndexes: file_todo_pb_todo_category_proto_depIdxs,
		MessageInfos:      file_todo_pb_todo_category_proto_msgTypes,
	}.Build()
	File_todo_pb_todo_category_proto = out.File
	file_todo_pb_todo_category_proto_rawDesc = nil
	file_todo_pb_todo_category_proto_goTypes = nil
	file_todo_pb_todo_category_proto_depIdxs = nil
}
