version: "3.9"

services:
  todo-db:
    container_name: todo-db
    image: postgres:latest
    restart: always
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=go_rabbitmq
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    networks:
      - todo-network
  todo-redis:
    container_name: todo-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - todo-network
    restart: always
  todo-gateway:
    container_name: todo-gateway
    image: arvians/go-todo-gateway:latest
    environment:
      - STATE=production
      - USER_SERVICE_URL=todo-user:50050
      - TODO_SERVICE_URL=todo-todo:50051
      - CATEGORY_SERVICE_URL=todo-category:50052
      - JAEGER_HOST=todo-jaeger
      - JAEGER_PORT=14268
      - REDIS_HOST=todo-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - MQ_HOST=todo-rabbitmq
      - MQ_USER=guest
      - MQ_PASSWORD=guest
      - MQ_PORT=5672
    ports:
      - "3000:3000"
    depends_on:
      - todo-db
    restart: always
    networks:
      - todo-network
  todo-user:
    container_name: todo-user
    image: arvians/go-todo-user:latest
    environment:
      - STATE=production
      - USER_SERVICE_URL=todo-user:50050
      - TODO_SERVICE_URL=todo-todo:50051
      - CATEGORY_SERVICE_URL=todo-category:50052
      - DB_HOST=todo-db
      - DB_PORT=5432
      - DB_DATABASE=go_rabbitmq
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_CONNECTION=postgres
      - DB_SSL_MODE=disable
      - DB_POOL_MIN=10
      - DB_POOL_MAX=60
      - DB_MAX_IDLE_TIME=60
      - DB_MAX_LIFE_TIME=60
      - JAEGER_HOST=todo-jaeger
      - JAEGER_PORT=14268
    ports:
      - "50050:50050"
    depends_on:
      - todo-db
    restart: always
    networks:
      - todo-network
  todo-todo:
    container_name: todo-todo
    image: arvians/go-todo-todo:latest
    environment:
      - STATE=production
      - USER_SERVICE_URL=todo-user:50050
      - TODO_SERVICE_URL=todo-todo:50051
      - CATEGORY_SERVICE_URL=todo-category:50052
      - DB_HOST=todo-db
      - DB_PORT=5432
      - DB_DATABASE=go_rabbitmq
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_CONNECTION=postgres
      - DB_SSL_MODE=disable
      - DB_POOL_MIN=10
      - DB_POOL_MAX=60
      - DB_MAX_IDLE_TIME=60
      - DB_MAX_LIFE_TIME=60
      - JAEGER_HOST=todo-jaeger
      - JAEGER_PORT=14268
    ports:
      - "50051:50051"
    depends_on:
      - todo-db
    restart: always
    networks:
      - todo-network
  todo-category:
    container_name: todo-category
    image: arvians/go-todo-category:latest
    environment:
      - STATE=production
      - USER_SERVICE_URL=todo-user:50050
      - TODO_SERVICE_URL=todo-todo:50051
      - CATEGORY_SERVICE_URL=todo-category:50052
      - DB_HOST=todo-db
      - DB_PORT=5432
      - DB_DATABASE=go_rabbitmq
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_CONNECTION=postgres
      - DB_SSL_MODE=disable
      - DB_POOL_MIN=10
      - DB_POOL_MAX=60
      - DB_MAX_IDLE_TIME=60
      - DB_MAX_LIFE_TIME=60
      - JAEGER_HOST=todo-jaeger
      - JAEGER_PORT=14268
    ports:
      - "50052:50052"
    depends_on:
      - todo-db
    restart: always
    networks:
      - todo-network
  todo-category_todo:
    container_name: todo-category-todo
    image: arvians/go-todo-category-todo:latest
    environment:
      - STATE=production
      - USER_SERVICE_URL=todo-user:50050
      - TODO_SERVICE_URL=todo-todo:50051
      - CATEGORY_SERVICE_URL=todo-category:50052
      - DB_HOST=todo-db
      - DB_PORT=5432
      - DB_DATABASE=go_rabbitmq
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_CONNECTION=postgres
      - DB_SSL_MODE=disable
      - DB_POOL_MIN=10
      - DB_POOL_MAX=60
      - DB_MAX_IDLE_TIME=60
      - DB_MAX_LIFE_TIME=60
      - JAEGER_HOST=todo-jaeger
      - JAEGER_PORT=14268
      - MQ_HOST=todo-rabbitmq
      - MQ_USER=guest
      - MQ_PASSWORD=guest
      - MQ_PORT=5672
    depends_on:
      - todo-db
    restart: always
    networks:
      - todo-network
  todo-worker:
    container_name: todo-worker
    image: arvians/go-todo-worker:latest
    restart: always
    environment:
      - STATE=production
      - MQ_HOST=todo-rabbitmq
      - MQ_USER=guest
      - MQ_PASSWORD=guest
      - MQ_PORT=5672
    networks:
      - todo-network
  todo-rabbitmq:
    container_name: todo-rabbitmq
    image: rabbitmq:3.11-management
    restart: always
    volumes:
      - ./database/rabbitmq/data:/var/lib/rabbitmq/
      - ./database/rabbitmq/log:/var/log/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - todo-network
  todo-jaeger:
    container_name: todo-jaeger
    image: jaegertracing/all-in-one:1.44
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
      - "6831:6831/udp"
      - "6832:6832/udp"
    restart: always
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
