version: "3.9"

services:
  todo-db:
    container_name: todo-db
    image: postgres:latest
    restart: always
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=go_rabbitmq
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    networks:
      - todo-network
  todo-redis:
    container_name: todo-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - todo-network
    restart: always
  todo-rabbitmq:
    container_name: todo-rabbitmq
    image: rabbitmq:3.11-management
    restart: always
    volumes:
      - ./database/rabbitmq/data:/var/lib/rabbitmq/
      - ./database/rabbitmq/log:/var/log/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - todo-network
  todo-jaeger:
    container_name: todo-jaeger
    image: jaegertracing/all-in-one:1.44
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
      - "6831:6831/udp"
      - "6832:6832/udp"
    restart: always
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
