CREATE TABLE IF NOT EXISTS category_todos(
   id serial PRIMARY KEY,
   name VARCHAR (50) NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
