CREATE TABLE IF NOT EXISTS category_todo(
    todo_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    FOREIGN KEY (todo_id) REFERENCES todos(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE ON UPDATE CASCADE
);
